### ISSUE TITLE
Revise "Why not?" section, re: Geospatial analysis

### ISSUE THREAD

**Issue by dannguyen** [jsvine/intro-to-visidata#14]
The section titled ["Why not use Visidata?"](https://jsvine.github.io/intro-to-visidata/the-big-picture/what-is-visidata/?highlight=geospatial) currently states, under the subhed "Geospatial analysis":

> VisiData can read geospatial data, but doesn’t have many features for analyzing it.

Suggest: Move subhed to "Why use Visidata?", change it to:

> VisiData can read geospatial data and do [this](https://www.youtube.com/watch?v=N1CBDTgGtOU).
 ##
And insert gif animation from  [3:32 time in PyCascades lightning talk](https://youtu.be/N1CBDTgGtOU?t=212)

![image](https://user-images.githubusercontent.com/121520/58698416-e0047b80-8360-11e9-986d-a144c3a306f1.png)

**Comment by jsvine** [comment]
Hahahah, I can't remember the last time I smiled at PR :^)

That demo is, indeed, pretty neat. My caution with geospatial data was meant more like: You can't do spatial joins et cetera. But maybe that's too arcane of a point. I'll think on this. In the meantime: any thoughts/preferences, @saulpw?

**Comment by saulpw** [comment]
Well, you know how I love the graphing features of VisiData :) But I agree, that it's a bit far-fetched to call those features "geospatial analysis", since it's just the simplest projection and the only analysis you can do is visual inspection and select points within a bounding box.  Also maybe a shapefile example would be more appropriate?  At least it's literally drawing map data, instead of the lat/long graph hackery shown in the video.

This might also be a good time to ask, what might be good geospatial analysis features that VisiData could reasonably include?  Simple overlays of two maps/graphs?  Some kind of join, such that you can see which row/polygon in a .shp these lat/long coords are inside?

**Comment by jsvine** [comment]
Re. this specific PR, I'm leaning toward just not mentioning geospatial stuff as either a top-level pro *or* con. But it does seem worth adding a short chapter to the tutorial on geospatial analysis and display.

Re. @saulpw's question: I think the most immediately useful would be spatial joins, especially point-in-polygon, for quick things like (taking your demo as an example): Which neighborhood has the highest ratio of mouse sightings to rat sightings? Getting that sorted out would likely require adding coordinate reprojections, which ... hooooo ... sure you want to sign up for that, Saul?

(And, yeah, overlays *would* be neat, and feel like a sort of natural extension of the work that joins would require ... but you'd know better than I would.)

**Comment by saulpw** [comment]
Yeah, dealing with projections sounds like a major pain.  But if there is a Python library that does most of the heavy lifting, then it might be well worth it.  VisiData is really just a nice interface for Python and its ecosystem :)

I'd been thinking of overlays as "two sheets on the same grid" but your intuition around doing it with joins just turned that on its head.  Now I'm thinking we could add the `polygon`, `polyline`, and `point` column types, and making it easy to construct maps/drawings with any combination of those columns (like how we can use graphs already).  Normal joins could then generate overlays, and we'd add a join on X-in-polygon, with the standard jointypes applying by very reasonable extension.  I think that would cover a lot of ground, even before the inevitable geocoding plugin.

It all starts with finding a decent Python library, a sample dataset, and some example Python code that uses the library on the dataset.  I'm not going to go looking for it, but if trouble showed up on my doorstep I would probably at least invite it in for tea...

**Comment by jsvine** [comment]
Ha! Here's some of that potential "trouble":

> It all starts with finding a decent Python library,

For geospatial work in Python, I've mostly used [GeoPandas](https://geopandas.readthedocs.io/en/latest/) for high-level operations (joining, etc.), and [Fiona](https://fiona.readthedocs.io/en/latest/README.html) + [pyproj](https://pyproj4.github.io/pyproj/v2.2.0rel/) for lower-level operations. 

>  a sample dataset, 

For points, maybe NYC's "facilities database"?: https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-selfac.page ([documentation](http://docs.capitalplanning.nyc/facdb/))

For polygons, perhaps NYC's neighborhood boundaries: https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-nynta.page

> some example Python code 

Hmm, don't have any on hand for the NYC stuff. But GeoPandas' tutorial has some concrete examples, more generally: https://geopandas.readthedocs.io/en/latest/mergingdata.html

**Comment by dannguyen** [comment]
OK this PR request was half in jest, since the in-terminal geo visualization is very cool even if it isn't "proper" spatial analysis...I haven't tried to do much spatial analysis in Python myself (usually I go into postgres/postgis, or R), but maybe this issue in the visidata repo about enabling spatiallite is related:

https://github.com/saulpw/visidata/issues/291

(which I think Geopandas uses anyway?)

I really have no idea what would be the best visualization interface/output (in terms of what's possible). But even just being able to filter via spatial join -- e.g. given a column of shapedata (points, polygons, etc), filter the data to show records that are inside/intersect a given polygon. Or also, filter/sort by distance. This all sounds like big enough for its own plugin though...

Here's an example I've used in a past class -- joining crime data (points) to police precinct shapefiles. This is the PostGIS version:

http://2015.padjo.org/tutorials/mapping/022-joining-crime-data-to-nypd-precinct-map/

crime data csv: https://github.com/datahoarder/nypd-historical-crime-stats/raw/master/data/compiled/nypd-precinct-historical-crime-data.csv

NYPD precinct shapefiles on CARTO: https://daannguyen.carto.com/tables/nypd_precincts/public/map

(there's a download link at the bottom, or you could get them on the city site: https://data.cityofnewyork.us/Public-Safety/Police-Precincts/78dh-3ptz)

**Comment by anjakefala** [comment]
> OK this PR request was half in jest

@dannguyen Data artists/nerds are in the business of taking things said in jest very, very seriously. 🙃 

"Yes...sure...But WHAT IF?"
