### ISSUE TITLE
Shift-J/K does not move the column left or right (but Shift-H/L does)

### ISSUE THREAD

**Issue by dz-at-tc** [jsvine/intro-to-visidata#16]
The 2nd note in the [How to create an expression column](https://jsvine.github.io/intro-to-visidata/intermediate/creating-new-columns/#how-to-create-an-expression-column) section contains the following assertion:

> As always, you can move the column left or right using Shift-J and Shift-K.

I'm brand new to visidata but I'm pretty sure you want Shift-H and Shift-L there, respectively.

In any event, thank you for this excellent tutorial for this incredible tool!  I only wish I had known about it earlier...

**Comment by jsvine** [comment]
Thanks for the perceptive catch, @dz-at-tc! Appreciate it. Repo and live version have now been updated to fix this.
