### ISSUE TITLE
Potential issue with rendering on Chrome

### ISSUE THREAD

**Issue by jsvine** [jsvine/intro-to-visidata#37]
Flagged by @reagle in https://github.com/saulpw/visidata/issues/1418, picking it up here.

> Figures in the documentation don't look correct in google-chrome/103.0.5060.53 on macOS 12.4 21F79 arm64.

![image](https://user-images.githubusercontent.com/534702/176507375-2bc1a96c-3ccd-4abc-805e-796a343aa610.png)

**Comment by jsvine** [comment]
Unfortunately, I can't seem to get this to reproduce on MacOS with the same Chrome version. For me, it looks as intended:

<img width="842" alt="Screen Shot 2022-06-29 at 2 18 35 PM" src="https://user-images.githubusercontent.com/534702/176507909-f9a431a1-4f90-481f-9152-ab47136e2a2c.png">
 
So, a few follow-up questions, based on a hunch that it may have something to do with fonts:

- Do you happen to have network requests to Google Fonts blocked?

- Do you happen to have any custom font settings that would override a website's defaults? 

- Anything else font-related that might be specific to your setup?

**Comment by reagle** [comment]
I launched it as cleanly as I could and changed font settings for serif, sans, fixed, etc. It made no difference.

    open /Applications/Google\ Chrome.app --args --disable-extensions --disable-plugins --incognito --no-experiments --disable-remote-fonts https://jsvine.github.io/intro-to-visidata/

**Comment by jsvine** [comment]
Thanks for those details. Running your command on my machine produces a slightly funky (because of disabled fonts) version, but not reproducing the line-wrapping issue in your original screenshot:

<img width="753" alt="Screen Shot 2022-06-29 at 3 04 03 PM" src="https://user-images.githubusercontent.com/534702/176516060-13236b69-6df7-49d9-ba57-5031e13668c5.png">

On your machine, what happens if you remove the ` --disable-remote-fonts` flag?

**Comment by reagle** [comment]
In the command above, you can see I passed that flag too. It makes no difference either way.

**Comment by jsvine** [comment]
Hm, then I'm a bit stumped, given that I can't reproduce those results with the given command (or more generally). But I'll leave this issue open for a while in case other folks have the same issue / can help triangulate.

**Comment by reagle** [comment]
BTW: still present in Version 104.0.5112.79 (Official Build) (arm64), even when launching with Incognito. Oddly, it doesn't show in Brave, which uses the same renderer for the most part.

**Comment by jsvine** [comment]
Thanks for the update, @reagle. Strange, indeed!

**Comment by daviewales** [comment]
I'm getting this in Firefox 104.0.1 on Windows 11.
Changing `min-width` on `.ansihtml` from 696px to 790px it fixes it. (sort of...)
But then it protrudes out the right hand side of the body text.

I also don't see any fonts loading in the Network tab of the inspector.

**Comment by jsvine** [comment]
Thanks for letting me know! Could you (and @reagle, if possible) follow these instructions to determine which font the browser is actually using for the terminal-imitation?: https://stackoverflow.com/a/20830300

For instance, I get this:

<img width="1427" alt="Screen Shot 2022-09-06 at 9 21 14 PM" src="https://user-images.githubusercontent.com/534702/188767896-cccdf649-fd06-4113-b39f-ef7f12332506.png">

**Comment by daviewales** [comment]
On my mac it works, and looks the same as above.
On my work Windows 11, I get the following:

![image](https://user-images.githubusercontent.com/2499066/188849889-c2c571bf-93a2-4d07-bd72-c3bb40383d79.png)

My comment above about not seeing fonts load was a red herring, as they do load if I disable the browser cache:

![image](https://user-images.githubusercontent.com/2499066/188850411-1d9d4b7f-3390-4431-8430-ddbd7e5153b4.png)

**Comment by daviewales** [comment]
Actually... I think I figured it out.
I've set my minimum font size in Firefox to 13.
If I change it back to 12, it fixes the issue. (after a page reload)

![image](https://user-images.githubusercontent.com/2499066/188851395-868657a4-fbde-44c7-ae76-30ac79ca7b1f.png)

![image](https://user-images.githubusercontent.com/2499066/188851727-6d9409f9-fe59-429c-89e6-8102c5de42ce.png)

**Comment by daviewales** [comment]
Perhaps setting the min-width property in terms of relative units such as `em` or `ch` might help it scale with font size?

**Comment by reagle** [comment]
@daviewales, similarly, if I set my minimum font size to 11, it looks good. The degree to which it is larger than that corresponds with how mangled the table looks. (I keep mine at 14.)

**Comment by reagle** [comment]
@jsvine, Roboto Mono?

![SCR-20220907-bn1](https://user-images.githubusercontent.com/596814/188877358-3d0b3e32-e2e2-44c0-8861-822be694fc9e.png)

**Comment by jsvine** [comment]
Thank you @daviewales and @reagle! I think we've nailed down the source of the issue, those minimum font sizes. I'll try to come up with a fix.

**Comment by jsvine** [comment]
I *think* I may have fixed this! ([c07fdb3](https://github.com/jsvine/intro-to-visidata/commit/c07fdb397a5f42858d5fb6ba4206fa3a68a2d0b8)) `ch` did the trick.  Take a look when you have a chance and let me know.

**Comment by reagle** [comment]
Hi @jsvine, thanks for having a go. I do believe this change is live. And, if so, it does look different. I suppose in Chrome it look _better_ (but still not right) but it also looks not right in Firefox. It does look good in Safari. 

<img width="856" alt="chrome" src="https://github.com/jsvine/intro-to-visidata/assets/596814/c01c259d-5237-438f-93d8-dd7ee84f78a4">

<img width="791" alt="firefox" src="https://github.com/jsvine/intro-to-visidata/assets/596814/75297818-bb41-4e93-a879-39ae19e4ecc1">

<img width="743" alt="safari" src="https://github.com/jsvine/intro-to-visidata/assets/596814/50bf7b2d-ba82-43cd-a9bf-11c6808b69cd">

**Comment by jsvine** [comment]
Thanks; looks like I didn't test quite enough different pages in quite enough browsers. Have now pushed a tiny tweak that might(?) resolve this.

**Comment by reagle** [comment]
Great! FF now looks like Safari.  And Chrome overflows the text area a bit, but it's perfectly legible.

<img width="891" alt="SCR-20231117-qovr" src="https://github.com/jsvine/intro-to-visidata/assets/596814/6c633572-ca4d-4d19-878f-c224aec4619e">

**Comment by jsvine** [comment]
Great. I'm content to let the "terminal" overflow the text areas if the user has made the decision to set a minimum font size. Open to fixes down the road, but seems like a decent situation for now. Thanks again for flagging.
