### ISSUE TITLE
.txt file with pipe delimitation

### ISSUE THREAD

**Issue by underseacommunity** [jsvine/intro-to-visidata#38]
I have a .txt file with pipe delimitation that I am challenged with getting into visidata.  I am pretty sure it is unix or a really old system.  Merely changing the extension to .csc or tsv doesn't do the trick, should I use some of the loader specific options for files?  It has a header row and all that.

Also, I learned to code on a commodore 64 and some javascript when working on the OpenROV project out in the bay area....so I am beginner level.  Think your app is really cool, and if I can get it to work we can properly test some of our interface files with third party vendors.

**Comment by jsvine** [comment]
Hi @underseacommunity! Just a quick clarification: Neither I, nor this repository, nor the associated tutorial are officially part of the VisiData project. Accordingly, this question is probably better suited to the [official VisiData repository's discussion forum](https://github.com/saulpw/visidata/discussions/categories/q-a). But your questions is straightforward enough that I'm happy to answer it here. Plus, I like helping people to use the tool! So... 

I believe what you want is `vd my-file.txt -f tsv -d '|'`

... does that do the trick?

**Comment by underseacommunity** [comment]
I typed what you provided above except with a .csv extension and it looks a lot better now (somewhat discernable) but not exactly what I am looking for, however it is progress. VD just doesn't want to open a .txt file for me yet....  I will study what you have above along with the reference before I ask any more questions....really appreciate this!!

**Comment by jsvine** [comment]
Roger that! If the above doesn't work, there may be an issue with the file itself. If you're able to attach it here, I can take a look.
