### ISSUE TITLE
Clarify how to configure case-sensitive searches

### ISSUE THREAD

**Issue by rschwiebert** [jsvine/intro-to-visidata#41]
The docs say

> Searches in VisiData are, by default, case-insensitive. You can change this in [VisiData’s options](https://jsvine.github.io/intro-to-visidata/advanced/configuring-visidata).

It took me entirely too long to figure out that `regex_flags` is the relevant flag, and that is defaulting to `I`. Honestly I'd never seen the `re.compile` options used before.  And then it took a little bit longer to determine that configuring the setting `= ''` and not `= ` was necessary.

I think it'd be helpful to be explicit about it.

**Comment by jsvine** [comment]
Thanks for flagging this, @rschwiebert! I agree with your assessment. I'll aim to make the instructions more explicit in the next update.

**Comment by radostyle** [comment]
I also had this issue.  It took a long time to find out how to do this.  I came to this bug report to find out how to make case sensitive searches. Would at least be nice to have case-sensistivity or something in the regex_flag description so you can find it when searching.

**Comment by saulpw** [comment]
@radostyle what version are you using?  In develop branch (soon to be 3.0) there's a side panel with help information for the flags.

**Comment by jsvine** [comment]
Thanks for flagging @rschwiebert, thanks for the seconding @radostyle, and thanks for the preview @saulpw. For now, I've addressed this in f73c51e, now live:

<img width="751" alt="Screenshot" src="https://github.com/jsvine/intro-to-visidata/assets/534702/4b2e7ac0-725c-4730-a9f1-f53609f3f240">

Closing for now, but feel free to continue the conversation and/or propose better phrasing.

**Comment by rschwiebert** [comment]
@jsvine Thanks!

**Comment by radostyle** [comment]
Nice, Thanks!
