### ISSUE TITLE
Minor change suggested for the Distinctive Birds practical exercise

### ISSUE THREAD

**Issue by ezequiel-garzon** [jsvine/intro-to-visidata#42]
First of all, thanks a lot for such a wonderful tutorial for such an amazing tool. I have just finished it, hoping there is more to come. I'm pretty sure in the last part of the _Distinctive Birds_ practical exercise "Mourning Doves in Arizona and Missouri" should be "Mourning Doves in Arizona and Mississippi", referencing AZ and MS respectively. Cheers!

**Comment by jsvine** [comment]
Thank you, @ezequiel-garzon! Great catch, now fixed.
